server:
  port: 9697
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8888}/eureka/
spring:
  application:
    name: IDENTITY-SERVICE
    
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security_learning
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        hbm2ddl:
          auto: update
#          auto: create-drop
        show_sql: false
        
